//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebApiServices.WsSeguridad {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SoaServiceSoap", Namespace="http://tempuri.org/")]
    public partial class SoaService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ListarInformesPDFPatCoreOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarInformeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SoaService() {
            this.Url = global::WebApiServices.Properties.Settings.Default.WebApiServices_WsSeguridad_SoaService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ListarInformesPDFPatCoreCompletedEventHandler ListarInformesPDFPatCoreCompleted;
        
        /// <remarks/>
        public event ActualizarInformeCompletedEventHandler ActualizarInformeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarInformesPDFPatCore", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ListarInformesPDFPatCore(string tocken, string IdCliente, int IdOrdenAtencion, int Linea) {
            object[] results = this.Invoke("ListarInformesPDFPatCore", new object[] {
                        tocken,
                        IdCliente,
                        IdOrdenAtencion,
                        Linea});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ListarInformesPDFPatCoreAsync(string tocken, string IdCliente, int IdOrdenAtencion, int Linea) {
            this.ListarInformesPDFPatCoreAsync(tocken, IdCliente, IdOrdenAtencion, Linea, null);
        }
        
        /// <remarks/>
        public void ListarInformesPDFPatCoreAsync(string tocken, string IdCliente, int IdOrdenAtencion, int Linea, object userState) {
            if ((this.ListarInformesPDFPatCoreOperationCompleted == null)) {
                this.ListarInformesPDFPatCoreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarInformesPDFPatCoreOperationCompleted);
            }
            this.InvokeAsync("ListarInformesPDFPatCore", new object[] {
                        tocken,
                        IdCliente,
                        IdOrdenAtencion,
                        Linea}, this.ListarInformesPDFPatCoreOperationCompleted, userState);
        }
        
        private void OnListarInformesPDFPatCoreOperationCompleted(object arg) {
            if ((this.ListarInformesPDFPatCoreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarInformesPDFPatCoreCompleted(this, new ListarInformesPDFPatCoreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarInforme", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ActualizarInforme(int Id, int IdCliente) {
            object[] results = this.Invoke("ActualizarInforme", new object[] {
                        Id,
                        IdCliente});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizarInformeAsync(int Id, int IdCliente) {
            this.ActualizarInformeAsync(Id, IdCliente, null);
        }
        
        /// <remarks/>
        public void ActualizarInformeAsync(int Id, int IdCliente, object userState) {
            if ((this.ActualizarInformeOperationCompleted == null)) {
                this.ActualizarInformeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarInformeOperationCompleted);
            }
            this.InvokeAsync("ActualizarInforme", new object[] {
                        Id,
                        IdCliente}, this.ActualizarInformeOperationCompleted, userState);
        }
        
        private void OnActualizarInformeOperationCompleted(object arg) {
            if ((this.ActualizarInformeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarInformeCompleted(this, new ActualizarInformeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ListarInformesPDFPatCoreCompletedEventHandler(object sender, ListarInformesPDFPatCoreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarInformesPDFPatCoreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarInformesPDFPatCoreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ActualizarInformeCompletedEventHandler(object sender, ActualizarInformeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarInformeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarInformeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591