//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebApiServices.WebSanna {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SoaServiceSoap", Namespace="http://tempuri.org/")]
    public partial class SoaService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsultaOAFerrerOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaOASanBorjaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaOAGolfOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaOAAliadaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SoaService() {
            this.Url = global::WebApiServices.Properties.Settings.Default.WebApiServices_WebSanna_SoaService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsultaOAFerrerCompletedEventHandler ConsultaOAFerrerCompleted;
        
        /// <remarks/>
        public event ConsultaOASanBorjaCompletedEventHandler ConsultaOASanBorjaCompleted;
        
        /// <remarks/>
        public event ConsultaOAGolfCompletedEventHandler ConsultaOAGolfCompleted;
        
        /// <remarks/>
        public event ConsultaOAAliadaCompletedEventHandler ConsultaOAAliadaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaOAFerrer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ConsultaOAFerrer(string OrdenAtencion, int TipoOrden, string Sucursal, string NombreCompleto, string Documento) {
            object[] results = this.Invoke("ConsultaOAFerrer", new object[] {
                        OrdenAtencion,
                        TipoOrden,
                        Sucursal,
                        NombreCompleto,
                        Documento});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaOAFerrerAsync(string OrdenAtencion, int TipoOrden, string Sucursal, string NombreCompleto, string Documento) {
            this.ConsultaOAFerrerAsync(OrdenAtencion, TipoOrden, Sucursal, NombreCompleto, Documento, null);
        }
        
        /// <remarks/>
        public void ConsultaOAFerrerAsync(string OrdenAtencion, int TipoOrden, string Sucursal, string NombreCompleto, string Documento, object userState) {
            if ((this.ConsultaOAFerrerOperationCompleted == null)) {
                this.ConsultaOAFerrerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaOAFerrerOperationCompleted);
            }
            this.InvokeAsync("ConsultaOAFerrer", new object[] {
                        OrdenAtencion,
                        TipoOrden,
                        Sucursal,
                        NombreCompleto,
                        Documento}, this.ConsultaOAFerrerOperationCompleted, userState);
        }
        
        private void OnConsultaOAFerrerOperationCompleted(object arg) {
            if ((this.ConsultaOAFerrerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaOAFerrerCompleted(this, new ConsultaOAFerrerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaOASanBorja", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ConsultaOASanBorja(string OrdenAtencion, int TipoOrden, string Unidad) {
            object[] results = this.Invoke("ConsultaOASanBorja", new object[] {
                        OrdenAtencion,
                        TipoOrden,
                        Unidad});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaOASanBorjaAsync(string OrdenAtencion, int TipoOrden, string Unidad) {
            this.ConsultaOASanBorjaAsync(OrdenAtencion, TipoOrden, Unidad, null);
        }
        
        /// <remarks/>
        public void ConsultaOASanBorjaAsync(string OrdenAtencion, int TipoOrden, string Unidad, object userState) {
            if ((this.ConsultaOASanBorjaOperationCompleted == null)) {
                this.ConsultaOASanBorjaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaOASanBorjaOperationCompleted);
            }
            this.InvokeAsync("ConsultaOASanBorja", new object[] {
                        OrdenAtencion,
                        TipoOrden,
                        Unidad}, this.ConsultaOASanBorjaOperationCompleted, userState);
        }
        
        private void OnConsultaOASanBorjaOperationCompleted(object arg) {
            if ((this.ConsultaOASanBorjaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaOASanBorjaCompleted(this, new ConsultaOASanBorjaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaOAGolf", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ConsultaOAGolf(string OrdenAtencion, int TipoOrden, string Unidad) {
            object[] results = this.Invoke("ConsultaOAGolf", new object[] {
                        OrdenAtencion,
                        TipoOrden,
                        Unidad});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaOAGolfAsync(string OrdenAtencion, int TipoOrden, string Unidad) {
            this.ConsultaOAGolfAsync(OrdenAtencion, TipoOrden, Unidad, null);
        }
        
        /// <remarks/>
        public void ConsultaOAGolfAsync(string OrdenAtencion, int TipoOrden, string Unidad, object userState) {
            if ((this.ConsultaOAGolfOperationCompleted == null)) {
                this.ConsultaOAGolfOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaOAGolfOperationCompleted);
            }
            this.InvokeAsync("ConsultaOAGolf", new object[] {
                        OrdenAtencion,
                        TipoOrden,
                        Unidad}, this.ConsultaOAGolfOperationCompleted, userState);
        }
        
        private void OnConsultaOAGolfOperationCompleted(object arg) {
            if ((this.ConsultaOAGolfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaOAGolfCompleted(this, new ConsultaOAGolfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaOAAliada", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ConsultaOAAliada(string OrdenAtencion, int TipoOrden, string Unidad) {
            object[] results = this.Invoke("ConsultaOAAliada", new object[] {
                        OrdenAtencion,
                        TipoOrden,
                        Unidad});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaOAAliadaAsync(string OrdenAtencion, int TipoOrden, string Unidad) {
            this.ConsultaOAAliadaAsync(OrdenAtencion, TipoOrden, Unidad, null);
        }
        
        /// <remarks/>
        public void ConsultaOAAliadaAsync(string OrdenAtencion, int TipoOrden, string Unidad, object userState) {
            if ((this.ConsultaOAAliadaOperationCompleted == null)) {
                this.ConsultaOAAliadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaOAAliadaOperationCompleted);
            }
            this.InvokeAsync("ConsultaOAAliada", new object[] {
                        OrdenAtencion,
                        TipoOrden,
                        Unidad}, this.ConsultaOAAliadaOperationCompleted, userState);
        }
        
        private void OnConsultaOAAliadaOperationCompleted(object arg) {
            if ((this.ConsultaOAAliadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaOAAliadaCompleted(this, new ConsultaOAAliadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ConsultaOAFerrerCompletedEventHandler(object sender, ConsultaOAFerrerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaOAFerrerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaOAFerrerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ConsultaOASanBorjaCompletedEventHandler(object sender, ConsultaOASanBorjaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaOASanBorjaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaOASanBorjaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ConsultaOAGolfCompletedEventHandler(object sender, ConsultaOAGolfCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaOAGolfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaOAGolfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ConsultaOAAliadaCompletedEventHandler(object sender, ConsultaOAAliadaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaOAAliadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaOAAliadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591