//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WCO_SedeCompartida
    {
        public int IdSede { get; set; }
        public int IdEmpresa { get; set; }
        public int IdSedeCompartida { get; set; }
    }
}
