//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WCO_UsuarioWeb
    {
        public string UserNameWeb { get; set; }
        public string PasswordWeb { get; set; }
        public string userHash { get; set; }
        public string estadoActualizacion { get; set; }
        public string tipoUserWeb { get; set; }
        public int IdPersona { get; set; }
        public Nullable<System.DateTime> fec_registro { get; set; }
        public int id { get; set; }
        public string ClasificadorMovimiento { get; set; }
    }
}
