//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebApiServices.WsSannaLab {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AppServiceSoap", Namespace="http://tempuri.org/")]
    public partial class AppService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsultaOAGolfOperationCompleted;
        
        private System.Threading.SendOrPostCallback MarcarEnviadoGolfOperationCompleted;
        
        private System.Threading.SendOrPostCallback GrupoSecuencialGolfOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaMigracionGolfOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnvioResultadoGolfOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaOASanBorjaOperationCompleted;
        
        private System.Threading.SendOrPostCallback MarcarEnviadoSanBorjaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GrupoSecuencialSanBorjaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaMigracionSanBorjaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaOAAliadaOperationCompleted;
        
        private System.Threading.SendOrPostCallback MarcarEnviadoAliadaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GrupoSecuencialAliadaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaMigracionAliadaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AppService() {
            this.Url = global::WebApiServices.Properties.Settings.Default.WebApiServices_WsSannaLab_AppService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsultaOAGolfCompletedEventHandler ConsultaOAGolfCompleted;
        
        /// <remarks/>
        public event MarcarEnviadoGolfCompletedEventHandler MarcarEnviadoGolfCompleted;
        
        /// <remarks/>
        public event GrupoSecuencialGolfCompletedEventHandler GrupoSecuencialGolfCompleted;
        
        /// <remarks/>
        public event ConsultaMigracionGolfCompletedEventHandler ConsultaMigracionGolfCompleted;
        
        /// <remarks/>
        public event EnvioResultadoGolfCompletedEventHandler EnvioResultadoGolfCompleted;
        
        /// <remarks/>
        public event ConsultaOASanBorjaCompletedEventHandler ConsultaOASanBorjaCompleted;
        
        /// <remarks/>
        public event MarcarEnviadoSanBorjaCompletedEventHandler MarcarEnviadoSanBorjaCompleted;
        
        /// <remarks/>
        public event GrupoSecuencialSanBorjaCompletedEventHandler GrupoSecuencialSanBorjaCompleted;
        
        /// <remarks/>
        public event ConsultaMigracionSanBorjaCompletedEventHandler ConsultaMigracionSanBorjaCompleted;
        
        /// <remarks/>
        public event ConsultaOAAliadaCompletedEventHandler ConsultaOAAliadaCompleted;
        
        /// <remarks/>
        public event MarcarEnviadoAliadaCompletedEventHandler MarcarEnviadoAliadaCompleted;
        
        /// <remarks/>
        public event GrupoSecuencialAliadaCompletedEventHandler GrupoSecuencialAliadaCompleted;
        
        /// <remarks/>
        public event ConsultaMigracionAliadaCompletedEventHandler ConsultaMigracionAliadaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaOAGolf", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ConsultaOAGolf(string OrdenAtencion, int TipoOrden, string Unidad) {
            object[] results = this.Invoke("ConsultaOAGolf", new object[] {
                        OrdenAtencion,
                        TipoOrden,
                        Unidad});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaOAGolfAsync(string OrdenAtencion, int TipoOrden, string Unidad) {
            this.ConsultaOAGolfAsync(OrdenAtencion, TipoOrden, Unidad, null);
        }
        
        /// <remarks/>
        public void ConsultaOAGolfAsync(string OrdenAtencion, int TipoOrden, string Unidad, object userState) {
            if ((this.ConsultaOAGolfOperationCompleted == null)) {
                this.ConsultaOAGolfOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaOAGolfOperationCompleted);
            }
            this.InvokeAsync("ConsultaOAGolf", new object[] {
                        OrdenAtencion,
                        TipoOrden,
                        Unidad}, this.ConsultaOAGolfOperationCompleted, userState);
        }
        
        private void OnConsultaOAGolfOperationCompleted(object arg) {
            if ((this.ConsultaOAGolfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaOAGolfCompleted(this, new ConsultaOAGolfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MarcarEnviadoGolf", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable MarcarEnviadoGolf(int IdOrdenAtención, string ListaLineaOA, int Medico, int Especialidad, string Usuario) {
            object[] results = this.Invoke("MarcarEnviadoGolf", new object[] {
                        IdOrdenAtención,
                        ListaLineaOA,
                        Medico,
                        Especialidad,
                        Usuario});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void MarcarEnviadoGolfAsync(int IdOrdenAtención, string ListaLineaOA, int Medico, int Especialidad, string Usuario) {
            this.MarcarEnviadoGolfAsync(IdOrdenAtención, ListaLineaOA, Medico, Especialidad, Usuario, null);
        }
        
        /// <remarks/>
        public void MarcarEnviadoGolfAsync(int IdOrdenAtención, string ListaLineaOA, int Medico, int Especialidad, string Usuario, object userState) {
            if ((this.MarcarEnviadoGolfOperationCompleted == null)) {
                this.MarcarEnviadoGolfOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMarcarEnviadoGolfOperationCompleted);
            }
            this.InvokeAsync("MarcarEnviadoGolf", new object[] {
                        IdOrdenAtención,
                        ListaLineaOA,
                        Medico,
                        Especialidad,
                        Usuario}, this.MarcarEnviadoGolfOperationCompleted, userState);
        }
        
        private void OnMarcarEnviadoGolfOperationCompleted(object arg) {
            if ((this.MarcarEnviadoGolfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MarcarEnviadoGolfCompleted(this, new MarcarEnviadoGolfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GrupoSecuencialGolf", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GrupoSecuencialGolf(int IdOrdenAtención, string LineaOrdenAtencion, int Grupo, string Usuario) {
            object[] results = this.Invoke("GrupoSecuencialGolf", new object[] {
                        IdOrdenAtención,
                        LineaOrdenAtencion,
                        Grupo,
                        Usuario});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GrupoSecuencialGolfAsync(int IdOrdenAtención, string LineaOrdenAtencion, int Grupo, string Usuario) {
            this.GrupoSecuencialGolfAsync(IdOrdenAtención, LineaOrdenAtencion, Grupo, Usuario, null);
        }
        
        /// <remarks/>
        public void GrupoSecuencialGolfAsync(int IdOrdenAtención, string LineaOrdenAtencion, int Grupo, string Usuario, object userState) {
            if ((this.GrupoSecuencialGolfOperationCompleted == null)) {
                this.GrupoSecuencialGolfOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGrupoSecuencialGolfOperationCompleted);
            }
            this.InvokeAsync("GrupoSecuencialGolf", new object[] {
                        IdOrdenAtención,
                        LineaOrdenAtencion,
                        Grupo,
                        Usuario}, this.GrupoSecuencialGolfOperationCompleted, userState);
        }
        
        private void OnGrupoSecuencialGolfOperationCompleted(object arg) {
            if ((this.GrupoSecuencialGolfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GrupoSecuencialGolfCompleted(this, new GrupoSecuencialGolfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaMigracionGolf", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ConsultaMigracionGolf(string OrdenAtencion, int TipoOrden, string Sucursal, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> FechaIni, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> FechaFin, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> Estado) {
            object[] results = this.Invoke("ConsultaMigracionGolf", new object[] {
                        OrdenAtencion,
                        TipoOrden,
                        Sucursal,
                        FechaIni,
                        FechaFin,
                        Estado});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaMigracionGolfAsync(string OrdenAtencion, int TipoOrden, string Sucursal, System.Nullable<System.DateTime> FechaIni, System.Nullable<System.DateTime> FechaFin, System.Nullable<int> Estado) {
            this.ConsultaMigracionGolfAsync(OrdenAtencion, TipoOrden, Sucursal, FechaIni, FechaFin, Estado, null);
        }
        
        /// <remarks/>
        public void ConsultaMigracionGolfAsync(string OrdenAtencion, int TipoOrden, string Sucursal, System.Nullable<System.DateTime> FechaIni, System.Nullable<System.DateTime> FechaFin, System.Nullable<int> Estado, object userState) {
            if ((this.ConsultaMigracionGolfOperationCompleted == null)) {
                this.ConsultaMigracionGolfOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaMigracionGolfOperationCompleted);
            }
            this.InvokeAsync("ConsultaMigracionGolf", new object[] {
                        OrdenAtencion,
                        TipoOrden,
                        Sucursal,
                        FechaIni,
                        FechaFin,
                        Estado}, this.ConsultaMigracionGolfOperationCompleted, userState);
        }
        
        private void OnConsultaMigracionGolfOperationCompleted(object arg) {
            if ((this.ConsultaMigracionGolfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaMigracionGolfCompleted(this, new ConsultaMigracionGolfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnvioResultadoGolf", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EnvioResultadoGolf(string Sucursal, string as_IdOrdenAtencion, string as_LineaOrdenAtencion, string as_OrdenAtencionProveedor, string as_NombreArchivo, string as_Diagnostico, string as_Extension, int Medico, int Especialidad, string Usuario, string pdfBase64) {
            object[] results = this.Invoke("EnvioResultadoGolf", new object[] {
                        Sucursal,
                        as_IdOrdenAtencion,
                        as_LineaOrdenAtencion,
                        as_OrdenAtencionProveedor,
                        as_NombreArchivo,
                        as_Diagnostico,
                        as_Extension,
                        Medico,
                        Especialidad,
                        Usuario,
                        pdfBase64});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EnvioResultadoGolfAsync(string Sucursal, string as_IdOrdenAtencion, string as_LineaOrdenAtencion, string as_OrdenAtencionProveedor, string as_NombreArchivo, string as_Diagnostico, string as_Extension, int Medico, int Especialidad, string Usuario, string pdfBase64) {
            this.EnvioResultadoGolfAsync(Sucursal, as_IdOrdenAtencion, as_LineaOrdenAtencion, as_OrdenAtencionProveedor, as_NombreArchivo, as_Diagnostico, as_Extension, Medico, Especialidad, Usuario, pdfBase64, null);
        }
        
        /// <remarks/>
        public void EnvioResultadoGolfAsync(string Sucursal, string as_IdOrdenAtencion, string as_LineaOrdenAtencion, string as_OrdenAtencionProveedor, string as_NombreArchivo, string as_Diagnostico, string as_Extension, int Medico, int Especialidad, string Usuario, string pdfBase64, object userState) {
            if ((this.EnvioResultadoGolfOperationCompleted == null)) {
                this.EnvioResultadoGolfOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnvioResultadoGolfOperationCompleted);
            }
            this.InvokeAsync("EnvioResultadoGolf", new object[] {
                        Sucursal,
                        as_IdOrdenAtencion,
                        as_LineaOrdenAtencion,
                        as_OrdenAtencionProveedor,
                        as_NombreArchivo,
                        as_Diagnostico,
                        as_Extension,
                        Medico,
                        Especialidad,
                        Usuario,
                        pdfBase64}, this.EnvioResultadoGolfOperationCompleted, userState);
        }
        
        private void OnEnvioResultadoGolfOperationCompleted(object arg) {
            if ((this.EnvioResultadoGolfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnvioResultadoGolfCompleted(this, new EnvioResultadoGolfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaOASanBorja", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ConsultaOASanBorja(string OrdenAtencion, int TipoOrden, string Unidad) {
            object[] results = this.Invoke("ConsultaOASanBorja", new object[] {
                        OrdenAtencion,
                        TipoOrden,
                        Unidad});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaOASanBorjaAsync(string OrdenAtencion, int TipoOrden, string Unidad) {
            this.ConsultaOASanBorjaAsync(OrdenAtencion, TipoOrden, Unidad, null);
        }
        
        /// <remarks/>
        public void ConsultaOASanBorjaAsync(string OrdenAtencion, int TipoOrden, string Unidad, object userState) {
            if ((this.ConsultaOASanBorjaOperationCompleted == null)) {
                this.ConsultaOASanBorjaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaOASanBorjaOperationCompleted);
            }
            this.InvokeAsync("ConsultaOASanBorja", new object[] {
                        OrdenAtencion,
                        TipoOrden,
                        Unidad}, this.ConsultaOASanBorjaOperationCompleted, userState);
        }
        
        private void OnConsultaOASanBorjaOperationCompleted(object arg) {
            if ((this.ConsultaOASanBorjaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaOASanBorjaCompleted(this, new ConsultaOASanBorjaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MarcarEnviadoSanBorja", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable MarcarEnviadoSanBorja(int IdOrdenAtención, string ListaLineaOA, int Medico, int Especialidad, string Usuario) {
            object[] results = this.Invoke("MarcarEnviadoSanBorja", new object[] {
                        IdOrdenAtención,
                        ListaLineaOA,
                        Medico,
                        Especialidad,
                        Usuario});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void MarcarEnviadoSanBorjaAsync(int IdOrdenAtención, string ListaLineaOA, int Medico, int Especialidad, string Usuario) {
            this.MarcarEnviadoSanBorjaAsync(IdOrdenAtención, ListaLineaOA, Medico, Especialidad, Usuario, null);
        }
        
        /// <remarks/>
        public void MarcarEnviadoSanBorjaAsync(int IdOrdenAtención, string ListaLineaOA, int Medico, int Especialidad, string Usuario, object userState) {
            if ((this.MarcarEnviadoSanBorjaOperationCompleted == null)) {
                this.MarcarEnviadoSanBorjaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMarcarEnviadoSanBorjaOperationCompleted);
            }
            this.InvokeAsync("MarcarEnviadoSanBorja", new object[] {
                        IdOrdenAtención,
                        ListaLineaOA,
                        Medico,
                        Especialidad,
                        Usuario}, this.MarcarEnviadoSanBorjaOperationCompleted, userState);
        }
        
        private void OnMarcarEnviadoSanBorjaOperationCompleted(object arg) {
            if ((this.MarcarEnviadoSanBorjaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MarcarEnviadoSanBorjaCompleted(this, new MarcarEnviadoSanBorjaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GrupoSecuencialSanBorja", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GrupoSecuencialSanBorja(int IdOrdenAtención, string LineaOrdenAtencion, int Grupo, string Usuario) {
            object[] results = this.Invoke("GrupoSecuencialSanBorja", new object[] {
                        IdOrdenAtención,
                        LineaOrdenAtencion,
                        Grupo,
                        Usuario});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GrupoSecuencialSanBorjaAsync(int IdOrdenAtención, string LineaOrdenAtencion, int Grupo, string Usuario) {
            this.GrupoSecuencialSanBorjaAsync(IdOrdenAtención, LineaOrdenAtencion, Grupo, Usuario, null);
        }
        
        /// <remarks/>
        public void GrupoSecuencialSanBorjaAsync(int IdOrdenAtención, string LineaOrdenAtencion, int Grupo, string Usuario, object userState) {
            if ((this.GrupoSecuencialSanBorjaOperationCompleted == null)) {
                this.GrupoSecuencialSanBorjaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGrupoSecuencialSanBorjaOperationCompleted);
            }
            this.InvokeAsync("GrupoSecuencialSanBorja", new object[] {
                        IdOrdenAtención,
                        LineaOrdenAtencion,
                        Grupo,
                        Usuario}, this.GrupoSecuencialSanBorjaOperationCompleted, userState);
        }
        
        private void OnGrupoSecuencialSanBorjaOperationCompleted(object arg) {
            if ((this.GrupoSecuencialSanBorjaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GrupoSecuencialSanBorjaCompleted(this, new GrupoSecuencialSanBorjaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaMigracionSanBorja", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ConsultaMigracionSanBorja(string OrdenAtencion, int TipoOrden, string Sucursal, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> FechaIni, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> FechaFin, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> Estado) {
            object[] results = this.Invoke("ConsultaMigracionSanBorja", new object[] {
                        OrdenAtencion,
                        TipoOrden,
                        Sucursal,
                        FechaIni,
                        FechaFin,
                        Estado});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaMigracionSanBorjaAsync(string OrdenAtencion, int TipoOrden, string Sucursal, System.Nullable<System.DateTime> FechaIni, System.Nullable<System.DateTime> FechaFin, System.Nullable<int> Estado) {
            this.ConsultaMigracionSanBorjaAsync(OrdenAtencion, TipoOrden, Sucursal, FechaIni, FechaFin, Estado, null);
        }
        
        /// <remarks/>
        public void ConsultaMigracionSanBorjaAsync(string OrdenAtencion, int TipoOrden, string Sucursal, System.Nullable<System.DateTime> FechaIni, System.Nullable<System.DateTime> FechaFin, System.Nullable<int> Estado, object userState) {
            if ((this.ConsultaMigracionSanBorjaOperationCompleted == null)) {
                this.ConsultaMigracionSanBorjaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaMigracionSanBorjaOperationCompleted);
            }
            this.InvokeAsync("ConsultaMigracionSanBorja", new object[] {
                        OrdenAtencion,
                        TipoOrden,
                        Sucursal,
                        FechaIni,
                        FechaFin,
                        Estado}, this.ConsultaMigracionSanBorjaOperationCompleted, userState);
        }
        
        private void OnConsultaMigracionSanBorjaOperationCompleted(object arg) {
            if ((this.ConsultaMigracionSanBorjaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaMigracionSanBorjaCompleted(this, new ConsultaMigracionSanBorjaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaOAAliada", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ConsultaOAAliada(string OrdenAtencion, int TipoOrden, string Unidad) {
            object[] results = this.Invoke("ConsultaOAAliada", new object[] {
                        OrdenAtencion,
                        TipoOrden,
                        Unidad});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaOAAliadaAsync(string OrdenAtencion, int TipoOrden, string Unidad) {
            this.ConsultaOAAliadaAsync(OrdenAtencion, TipoOrden, Unidad, null);
        }
        
        /// <remarks/>
        public void ConsultaOAAliadaAsync(string OrdenAtencion, int TipoOrden, string Unidad, object userState) {
            if ((this.ConsultaOAAliadaOperationCompleted == null)) {
                this.ConsultaOAAliadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaOAAliadaOperationCompleted);
            }
            this.InvokeAsync("ConsultaOAAliada", new object[] {
                        OrdenAtencion,
                        TipoOrden,
                        Unidad}, this.ConsultaOAAliadaOperationCompleted, userState);
        }
        
        private void OnConsultaOAAliadaOperationCompleted(object arg) {
            if ((this.ConsultaOAAliadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaOAAliadaCompleted(this, new ConsultaOAAliadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MarcarEnviadoAliada", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable MarcarEnviadoAliada(int IdOrdenAtención, string ListaLineaOA, int Medico, int Especialidad, string Usuario) {
            object[] results = this.Invoke("MarcarEnviadoAliada", new object[] {
                        IdOrdenAtención,
                        ListaLineaOA,
                        Medico,
                        Especialidad,
                        Usuario});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void MarcarEnviadoAliadaAsync(int IdOrdenAtención, string ListaLineaOA, int Medico, int Especialidad, string Usuario) {
            this.MarcarEnviadoAliadaAsync(IdOrdenAtención, ListaLineaOA, Medico, Especialidad, Usuario, null);
        }
        
        /// <remarks/>
        public void MarcarEnviadoAliadaAsync(int IdOrdenAtención, string ListaLineaOA, int Medico, int Especialidad, string Usuario, object userState) {
            if ((this.MarcarEnviadoAliadaOperationCompleted == null)) {
                this.MarcarEnviadoAliadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMarcarEnviadoAliadaOperationCompleted);
            }
            this.InvokeAsync("MarcarEnviadoAliada", new object[] {
                        IdOrdenAtención,
                        ListaLineaOA,
                        Medico,
                        Especialidad,
                        Usuario}, this.MarcarEnviadoAliadaOperationCompleted, userState);
        }
        
        private void OnMarcarEnviadoAliadaOperationCompleted(object arg) {
            if ((this.MarcarEnviadoAliadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MarcarEnviadoAliadaCompleted(this, new MarcarEnviadoAliadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GrupoSecuencialAliada", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GrupoSecuencialAliada(int IdOrdenAtención, string LineaOrdenAtencion, int Grupo, string Usuario) {
            object[] results = this.Invoke("GrupoSecuencialAliada", new object[] {
                        IdOrdenAtención,
                        LineaOrdenAtencion,
                        Grupo,
                        Usuario});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GrupoSecuencialAliadaAsync(int IdOrdenAtención, string LineaOrdenAtencion, int Grupo, string Usuario) {
            this.GrupoSecuencialAliadaAsync(IdOrdenAtención, LineaOrdenAtencion, Grupo, Usuario, null);
        }
        
        /// <remarks/>
        public void GrupoSecuencialAliadaAsync(int IdOrdenAtención, string LineaOrdenAtencion, int Grupo, string Usuario, object userState) {
            if ((this.GrupoSecuencialAliadaOperationCompleted == null)) {
                this.GrupoSecuencialAliadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGrupoSecuencialAliadaOperationCompleted);
            }
            this.InvokeAsync("GrupoSecuencialAliada", new object[] {
                        IdOrdenAtención,
                        LineaOrdenAtencion,
                        Grupo,
                        Usuario}, this.GrupoSecuencialAliadaOperationCompleted, userState);
        }
        
        private void OnGrupoSecuencialAliadaOperationCompleted(object arg) {
            if ((this.GrupoSecuencialAliadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GrupoSecuencialAliadaCompleted(this, new GrupoSecuencialAliadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaMigracionAliada", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ConsultaMigracionAliada(string OrdenAtencion, int TipoOrden, string Sucursal, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> FechaIni, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> FechaFin, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> Estado) {
            object[] results = this.Invoke("ConsultaMigracionAliada", new object[] {
                        OrdenAtencion,
                        TipoOrden,
                        Sucursal,
                        FechaIni,
                        FechaFin,
                        Estado});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaMigracionAliadaAsync(string OrdenAtencion, int TipoOrden, string Sucursal, System.Nullable<System.DateTime> FechaIni, System.Nullable<System.DateTime> FechaFin, System.Nullable<int> Estado) {
            this.ConsultaMigracionAliadaAsync(OrdenAtencion, TipoOrden, Sucursal, FechaIni, FechaFin, Estado, null);
        }
        
        /// <remarks/>
        public void ConsultaMigracionAliadaAsync(string OrdenAtencion, int TipoOrden, string Sucursal, System.Nullable<System.DateTime> FechaIni, System.Nullable<System.DateTime> FechaFin, System.Nullable<int> Estado, object userState) {
            if ((this.ConsultaMigracionAliadaOperationCompleted == null)) {
                this.ConsultaMigracionAliadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaMigracionAliadaOperationCompleted);
            }
            this.InvokeAsync("ConsultaMigracionAliada", new object[] {
                        OrdenAtencion,
                        TipoOrden,
                        Sucursal,
                        FechaIni,
                        FechaFin,
                        Estado}, this.ConsultaMigracionAliadaOperationCompleted, userState);
        }
        
        private void OnConsultaMigracionAliadaOperationCompleted(object arg) {
            if ((this.ConsultaMigracionAliadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaMigracionAliadaCompleted(this, new ConsultaMigracionAliadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ConsultaOAGolfCompletedEventHandler(object sender, ConsultaOAGolfCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaOAGolfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaOAGolfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void MarcarEnviadoGolfCompletedEventHandler(object sender, MarcarEnviadoGolfCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MarcarEnviadoGolfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MarcarEnviadoGolfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GrupoSecuencialGolfCompletedEventHandler(object sender, GrupoSecuencialGolfCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GrupoSecuencialGolfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GrupoSecuencialGolfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ConsultaMigracionGolfCompletedEventHandler(object sender, ConsultaMigracionGolfCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaMigracionGolfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaMigracionGolfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void EnvioResultadoGolfCompletedEventHandler(object sender, EnvioResultadoGolfCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnvioResultadoGolfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnvioResultadoGolfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ConsultaOASanBorjaCompletedEventHandler(object sender, ConsultaOASanBorjaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaOASanBorjaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaOASanBorjaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void MarcarEnviadoSanBorjaCompletedEventHandler(object sender, MarcarEnviadoSanBorjaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MarcarEnviadoSanBorjaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MarcarEnviadoSanBorjaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GrupoSecuencialSanBorjaCompletedEventHandler(object sender, GrupoSecuencialSanBorjaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GrupoSecuencialSanBorjaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GrupoSecuencialSanBorjaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ConsultaMigracionSanBorjaCompletedEventHandler(object sender, ConsultaMigracionSanBorjaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaMigracionSanBorjaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaMigracionSanBorjaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ConsultaOAAliadaCompletedEventHandler(object sender, ConsultaOAAliadaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaOAAliadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaOAAliadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void MarcarEnviadoAliadaCompletedEventHandler(object sender, MarcarEnviadoAliadaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MarcarEnviadoAliadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MarcarEnviadoAliadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GrupoSecuencialAliadaCompletedEventHandler(object sender, GrupoSecuencialAliadaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GrupoSecuencialAliadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GrupoSecuencialAliadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ConsultaMigracionAliadaCompletedEventHandler(object sender, ConsultaMigracionAliadaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaMigracionAliadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaMigracionAliadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591